allowBuilds:
  '@parcel/watcher': true
  esbuild: true

catalog:
  '@types/react': '^19.2.17'
  '@types/react-dom': '^19.2.5'
  react: '^19.2.8'
  react-dom: '^19.2.8'

packages:
  - 'apps/*'
  - 'packages/*'

publicHoistPattern:
  - svelte
