allowBuilds:
  '@parcel/watcher': true
  esbuild: true

catalog:
  '@types/react': '^19.3.0'
  '@types/react-dom': '^19.3.0'
  react: '^19.3.0'
  react-dom: '^19.3.0'

packages:
  - 'apps/*'
  - 'packages/*'

publicHoistPattern:
  - svelte
